//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FloodDataAccess.MarkerPointsModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MarkerPoint
    {
        public int Id { get; set; }
        public Guid UserID { get; set; }
        public DateTime CreatedOn { get; set; }
        public DateTime? Expiration { get; set; }
        public decimal Latitude { get; set; }
        public decimal Longitude { get; set; }
        public string Description { get; set; }
        public int? Severity { get; set; }
        public string UrlImage { get; set; }
    }
}
